development:
  bucket: developmentstore
  access_key_id: AKIAJTLGOIRPJ4C6UFAQ
  secret_access_key: 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

production:
  bucket: prodakshnstore
  access_key_id: AKIAJTLGOIRPJ4C6UFAQ
  secret_access_key: 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